# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnPrincipal.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_vtnPrincipal(object):
    def setupUi(self, vtnPrincipal):
        if not vtnPrincipal.objectName():
            vtnPrincipal.setObjectName(u"vtnPrincipal")
        vtnPrincipal.resize(586, 542)
        font = QFont()
        font.setPointSize(10)
        vtnPrincipal.setFont(font)
        self.centralwidget = QWidget(vtnPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblNombre = QLabel(self.centralwidget)
        self.lblNombre.setObjectName(u"lblNombre")
        self.lblNombre.setGeometry(QRect(20, 70, 69, 22))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setItalic(True)
        self.lblNombre.setFont(font1)
        self.lblApellido = QLabel(self.centralwidget)
        self.lblApellido.setObjectName(u"lblApellido")
        self.lblApellido.setGeometry(QRect(20, 110, 74, 22))
        self.lblApellido.setFont(font1)
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(110, 70, 291, 21))
        self.txtNombre.setMaxLength(20)
        self.txtApellido = QLineEdit(self.centralwidget)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setGeometry(QRect(110, 110, 291, 21))
        self.txtApellido.setFont(font)
        self.txtApellido.setMaxLength(20)
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(440, 390, 101, 41))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setUnderline(True)
        self.btnGuardar.setFont(font2)
        self.txtCedula = QLineEdit(self.centralwidget)
        self.txtCedula.setObjectName(u"txtCedula")
        self.txtCedula.setGeometry(QRect(110, 160, 151, 21))
        self.txtCedula.setFont(font)
        self.txtCedula.setMaxLength(10)
        self.lblCedula = QLabel(self.centralwidget)
        self.lblCedula.setObjectName(u"lblCedula")
        self.lblCedula.setGeometry(QRect(20, 160, 74, 22))
        self.lblCedula.setFont(font1)
        self.btnLimpiar = QPushButton(self.centralwidget)
        self.btnLimpiar.setObjectName(u"btnLimpiar")
        self.btnLimpiar.setGeometry(QRect(310, 390, 101, 41))
        self.btnLimpiar.setFont(font2)
        self.lblTipo_Curso = QLabel(self.centralwidget)
        self.lblTipo_Curso.setObjectName(u"lblTipo_Curso")
        self.lblTipo_Curso.setGeometry(QRect(20, 250, 131, 22))
        self.lblTipo_Curso.setFont(font1)
        self.cbTipo_Curso = QComboBox(self.centralwidget)
        self.cbTipo_Curso.addItem("")
        self.cbTipo_Curso.addItem("")
        self.cbTipo_Curso.addItem("")
        self.cbTipo_Curso.setObjectName(u"cbTipo_Curso")
        self.cbTipo_Curso.setGeometry(QRect(140, 250, 181, 22))
        self.lblcorreo = QLabel(self.centralwidget)
        self.lblcorreo.setObjectName(u"lblcorreo")
        self.lblcorreo.setGeometry(QRect(10, 210, 171, 22))
        self.lblcorreo.setFont(font1)
        self.txtCorreo = QLineEdit(self.centralwidget)
        self.txtCorreo.setObjectName(u"txtCorreo")
        self.txtCorreo.setGeometry(QRect(190, 210, 291, 21))
        self.txtCorreo.setFont(font)
        self.txtCorreo.setMaxLength(30)
        self.txtCorreo.setFrame(False)
        self.btnBuscar = QPushButton(self.centralwidget)
        self.btnBuscar.setObjectName(u"btnBuscar")
        self.btnBuscar.setGeometry(QRect(460, 0, 101, 41))
        self.btnBuscar.setFont(font2)
        self.btnActualizar = QPushButton(self.centralwidget)
        self.btnActualizar.setObjectName(u"btnActualizar")
        self.btnActualizar.setGeometry(QRect(50, 390, 101, 41))
        self.btnActualizar.setFont(font2)
        self.btnEliminar = QPushButton(self.centralwidget)
        self.btnEliminar.setObjectName(u"btnEliminar")
        self.btnEliminar.setGeometry(QRect(180, 390, 101, 41))
        self.btnEliminar.setFont(font2)
        self.txtBuscar_Cedula = QLineEdit(self.centralwidget)
        self.txtBuscar_Cedula.setObjectName(u"txtBuscar_Cedula")
        self.txtBuscar_Cedula.setGeometry(QRect(290, 20, 151, 21))
        self.txtBuscar_Cedula.setFont(font)
        self.txtBuscar_Cedula.setMaxLength(10)
        vtnPrincipal.setCentralWidget(self.centralwidget)
        self.txtBuscar_Cedula.raise_()
        self.lblApellido.raise_()
        self.txtNombre.raise_()
        self.txtApellido.raise_()
        self.btnGuardar.raise_()
        self.txtCedula.raise_()
        self.lblCedula.raise_()
        self.btnLimpiar.raise_()
        self.lblTipo_Curso.raise_()
        self.cbTipo_Curso.raise_()
        self.lblcorreo.raise_()
        self.txtCorreo.raise_()
        self.btnBuscar.raise_()
        self.btnActualizar.raise_()
        self.btnEliminar.raise_()
        self.lblNombre.raise_()
        self.statusbar = QStatusBar(vtnPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        vtnPrincipal.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtNombre, self.txtApellido)
        QWidget.setTabOrder(self.txtApellido, self.txtCedula)
        QWidget.setTabOrder(self.txtCedula, self.txtCorreo)
        QWidget.setTabOrder(self.txtCorreo, self.cbTipo_Curso)
        QWidget.setTabOrder(self.cbTipo_Curso, self.btnGuardar)
        QWidget.setTabOrder(self.btnGuardar, self.btnLimpiar)
        QWidget.setTabOrder(self.btnLimpiar, self.btnEliminar)
        QWidget.setTabOrder(self.btnEliminar, self.btnActualizar)
        QWidget.setTabOrder(self.btnActualizar, self.btnBuscar)

        self.retranslateUi(vtnPrincipal)

        QMetaObject.connectSlotsByName(vtnPrincipal)
    # setupUi

    def retranslateUi(self, vtnPrincipal):
        vtnPrincipal.setWindowTitle(QCoreApplication.translate("vtnPrincipal", u"Gestión de servicios de Universidad ", None))
        self.lblNombre.setText(QCoreApplication.translate("vtnPrincipal", u"Nombre:", None))
        self.lblApellido.setText(QCoreApplication.translate("vtnPrincipal", u"Apellido:", None))
        self.btnGuardar.setText(QCoreApplication.translate("vtnPrincipal", u"Guardar", None))
        self.lblCedula.setText(QCoreApplication.translate("vtnPrincipal", u"Cedula:", None))
        self.btnLimpiar.setText(QCoreApplication.translate("vtnPrincipal", u"Limpiar", None))
        self.lblTipo_Curso.setText(QCoreApplication.translate("vtnPrincipal", u"Tipo de Curso ", None))
        self.cbTipo_Curso.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.cbTipo_Curso.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Presencial", None))
        self.cbTipo_Curso.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"Virtual ", None))

        self.lblcorreo.setText(QCoreApplication.translate("vtnPrincipal", u"Correo Institucional:", None))
        self.btnBuscar.setText(QCoreApplication.translate("vtnPrincipal", u"Buscar", None))
        self.btnActualizar.setText(QCoreApplication.translate("vtnPrincipal", u"Actualizar", None))
        self.btnEliminar.setText(QCoreApplication.translate("vtnPrincipal", u"Eliminar ", None))
    # retranslateUi

